server:
  port: 8086

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/yhhbsz?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password:
  redis:
    host: localhost
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    locale: zh_CN
    time-zone: GMT+8
    default-property-inclusion: NON_EMPTY
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

sms:
  access_key: LTAI4tzTtdBeG8wX
  access_key_secret: KTjyBTaYmF6FiswAPWhN2HL3XqKtbi

mybatis:
  mapper-locations: classpath:mybatis/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

# 打印sql
logging:
  level:
     com.example.demo.dao : debug

dir:
  product: "/Users/liuchaoyang/Documents/java/demo/my-doctor/product/"
  banner: "/Users/liuchaoyang/Documents/java/demo/my-doctor/banner/"
---
spring:
  profiles: dev

---
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://39.106.31.166:3306/yhhbsz?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: liuchaoyang
dir:
  product: "/usr/local/mydoctor/file/product/"
  banner: "/usr/local/mydoctor/file/banner/"




